themarket/accounts/urls.py
from django.urls import path, re_path

from . views import (
        RetailerSignUpView,
        CustomerSignUpView,
        guest_register_view,
        AccountHomeView,
        )


app_name = 'accounts'
urlpatterns = [
    path("", guest_register_view, name='guest_register'),
    path("signup/retailer/", RetailerSignUpView.as_view(), name='retailer_signup'),
    path("signup/customer/", CustomerSignUpView.as_view(), name='customer_signup'),
    path("myaccount/", AccountHomeView.as_view(), name='account_home'),
]

themarket/carts/urls.py
from django.urls import path, re_path

from . views import (
        cart_home,
        cart_update,
        checkout_home,
        checkout_done_view
        )


app_name = 'carts'
urlpatterns = [
    path("", cart_home, name='home'),
    path("update/", cart_update, name='update'),
    path("checkout/", checkout_home, name='checkout'),
    path("checkout/success", checkout_done_view, name='success'),
]

themarket/products/urls.py
from django.urls import path, re_path

from . views import (
        product_list_view,
        #product_detail_view,
        product_detail_slug_view
        )


app_name = 'products'
urlpatterns = [
    path("", product_list_view, name='list'),
    #re_path(r'^(?P<pk>\d+)/?$', product_detail_view),
    re_path(r'^(?P<slug>\w+)/?$', product_detail_slug_view, name='detail'),
]

themarket/themarket/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from .views import home_page, about_page, contact_page
from accounts.views import login_page, register_page, guest_register_view
from django.contrib.auth.views import LogoutView

from django.conf import settings
from django.conf.urls.static import static

from addresses.views import checkout_address_create_view, checkout_address_reuse_view

urlpatterns = [
    path('', home_page, name='home'),
    path('about/', about_page, name='about'),
    path('contact/', contact_page, name='contact'),
    path('login/', login_page, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', register_page, name='register'),
    path('register/guest/', guest_register_view, name='guest_register'),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('search/', include('search.urls')),
    path('cart/', include('carts.urls')),
    path('checkout/address/create', checkout_address_create_view, name='checkout_address_create'),
    path('checkout/address/reuse', checkout_address_reuse_view, name='checkout_address_reuse'),
    
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

themarket/templates/base/css.html
{% load static %}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
crossorigin="anonymous">
<link rel="stylesheet" href="{% static "css/main.css" %}" >

<!-- Fontawesome icons cdn -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.1/css/all.css" integrity="sha384-O8whS3fhG2OnA5Kas0Y9l3cfpmYjapjI0E4theH4iuMD+pLhbf6JI0jIMfYcK3yZ" crossorigin="anonymous">

themarket/templates/base/js.html
{% load static %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
    crossorigin="anonymous"></script>

themarket/templates/base/nav.html
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'products:list' as product_list_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}
{% url 'carts:home' as cart_url %}
{% url 'accounts:account_home' as myaccount_url %}


<nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
    <div class='container'>
    <a class="navbar-brand" href="{{ home_url }}">{% if brand_name %} {{ brand_name }} {% else %}The Market {% endif %}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item {% if request.path == home_url %}active{% endif %}">
                <a class="nav-link" href="{{ home_url }}">Home
                    <span class="sr-only">(current)</span>
                </a>
            </li>
            <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
                <a class="nav-link" href="{{ contact_url }}">Contact</a>
            </li>
            <li class="nav-item {% if request.path == product_list_url %}active{% endif %}">
                <a class="nav-link" href="{{ product_list_url }}">Products</a>
            </li>
            
            <li class="nav-item {% if request.path == logout_url %}active{% endif %}">
                
            </li>
            
            
        </ul>
        {% include 'search/snippets/search_form.html' %}

        {% if request.user.is_authenticated %}
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Account
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item {% if request.path == myaccount_url %}active{% endif %}" href="{{ myaccount_url }}">My Account</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item {% if request.path == logout_url %}active{% endif %}" href="{{ logout_url }}?next={{request.path}}">Logout</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item {% if request.path == myproducts_url %}active{% endif %}" href="{% url 'admin:index' %}">My Products</a>
            </div>
            </li>
            <li class="nav-item">
        </li>
        {% else %}
            <li class="nav-item {% if request.path == register_url %}active{% endif %}">
                <a class="nav-link" href="{{ register_url }}">Register</a>
            </li>
            <li class="nav-item {% if request.path == login_url %}active{% endif %}">
                <a class="nav-link" href="{{ login_url }}">Login</a>
            </li>
            {% endif %}
        <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
            <a class="nav-link" href="{{ cart_url }}">{{ request.session.cart_items }} <i class="fas fa-shopping-cart"></i></a>
        </li>
    </div>
</div>
</nav>