themarket/accounts/urls.py
from django.urls import path, re_path

from . views import (
        RetailerSignUpView,
        CustomerSignUpView,
        guest_register_view,
        AccountHomeView,
        )


app_name = 'accounts'
urlpatterns = [
    path("", guest_register_view, name='guest_register'),
    path("signup/retailer/", RetailerSignUpView.as_view(), name='retailer_signup'),
    path("signup/customer/", CustomerSignUpView.as_view(), name='customer_signup'),
    path("myaccount/", AccountHomeView.as_view(), name='account_home'),
]

themarket/carts/urls.py
from django.urls import path, re_path

from . views import (
        cart_home,
        cart_update,
        checkout_home,
        checkout_done_view
        )


app_name = 'carts'
urlpatterns = [
    path("", cart_home, name='home'),
    path("update/", cart_update, name='update'),
    path("checkout/", checkout_home, name='checkout'),
    path("checkout/success", checkout_done_view, name='success'),
]

themarket/themarket/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from .views import home_page, about_page, contact_page
from accounts.views import login_page, register_page, guest_register_view
from django.contrib.auth.views import LogoutView

from django.conf import settings
from django.conf.urls.static import static

from addresses.views import checkout_address_create_view, checkout_address_reuse_view

urlpatterns = [
    path('', home_page, name='home'),
    path('about/', about_page, name='about'),
    path('contact/', contact_page, name='contact'),
    path('login/', login_page, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', register_page, name='register'),
    path('register/guest/', guest_register_view, name='guest_register'),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('search/', include('search.urls')),
    path('cart/', include('carts.urls')),
    path('checkout/address/create', checkout_address_create_view, name='checkout_address_create'),
    path('checkout/address/reuse', checkout_address_reuse_view, name='checkout_address_reuse'),
    
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

themarket/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Title</title>

    {% include 'base/css.html' %}
    
</head>

<body>
    {% include 'base/nav.html' %}
    <div class="container-fluid">
    {% block content %} {% endblock %}
    </div>

    {% include 'base/js.html' %}
</body>

</html>

themarket/templates/home_page.html
{% extends "base.html" %} 

{% load static %}

 {% block content %}

 <div class="container-fluid">
        <div class="hero-block home">
               <!--holder for hero image-->
           <div class="hero-text">
               <h1>Welcome to The Market</h1>
                <a href="{% url 'accounts:retailer_signup' %}" class="btn btn-primary btn-lg" role="button">Retailer Sign Up</a>
                <a href="{% url 'accounts:customer_signup' %}" class="btn btn-info btn-lg" role="button">Customer Sign Up</a>
           </div>
       </div>
       </div>

<div class="text-center my-3">
    <h1>Products</h1>
</div>

<div class="row">
    {% for obj in object_list %}
    <div class="col my-3">
        
        {% include 'products/snippets/card.html' with instance=obj %} 
        
    </div>
    {% endfor %}
</div>
        
   

{% endblock %}